### ISSUE TITLE
API 8 -> API 11

### ISSUE THREAD

**Issue by mastef** [byrobingames/localnotifications#2]
Ran into `cannot resolve method setLatestEventinfo` on Notification. Looks like it's depreciated and was removed in Android SDK 23+ - it should be updated to NotificationCompat.Builder : 

http://stackoverflow.com/a/32346246

**Comment by byrobingames** [comment]
Ok thanks.. for now no problem because we go till API 22 on Stencyl.com

**Comment by mastef** [comment]
Looks like this has been resolved with the switch to NotificationCompat
