### ISSUE TITLE
SharedPreferences

### ISSUE THREAD

**Issue by mastef** [byrobingames/localnotifications#3]
Hey @byrobingames, I'm currently updating the extension so it'd work with the newer SDK and some more options. I was wondering if you had a specific reason to use `SharedPreferences` instead of `Intent`?

It seems as if `SharedPreferences` forces currently multiple notifications to the same content as it's the same file that gets overwritten and called by each notification. The BroadcastReceiver ( `NCReceiver` ) is getting an Intent here :  [`public void onReceive(Context arg0, Intent arg1)`](https://github.com/byrobingames/localnotifications/blob/master/dependencies/android/src/com/byrobin/Notification/NCReceiver.java#L30) - any reason to not transfer the data in there?

**Comment by byrobingames** [comment]
Don't know made it a long time a go, i think at that time i did not think about multiple notifications

**Comment by mastef** [comment]
Might be interesting to change approach based on #4
