### ISSUE TITLE
MODE_WORLD_READABLE removed from SDK > 24-25

### ISSUE THREAD

**Issue by mastef** [byrobingames/localnotifications#4]
FYI : `MODE_WORLD_READABLE` stopped working with the latest SDKs, and Google recommends that SDK in case your app wants to be featured. I tested on Google Pixel ( Android N & O ) and it crashes with Security Exception

Worth checking if `MODE_PRIVATE` would still work with the solution ( e.g. the different notifications have access to it ) or changing the approach ( [#MODE_WORLD_READABLE](https://developer.android.com/reference/android/content/Context.html#MODE_WORLD_READABLE) )

https://stackoverflow.com/questions/39121052/java-lang-securityexception-mode-world-readable-no-longer-supported

**Comment by byrobingames** [comment]
change MODE_WORLD_READABLE to MODE_PRIVATE and works
