### ISSUE TITLE
Notifications only work when game is active.

### ISSUE THREAD

**Issue by wcoyote132** [byrobingames/localnotifications#6]
Hello, I've only tested this on android(haven't tested iOS yet).

It seems the notifications only work when the game is active or minimized and doesn't show any notifications when the game is closed.

**Comment by byrobingames** [comment]
When I tested (long time ago) it was showing notifications when the game was closed.
But there are Android updates... so maybe it does not work anymore.

It's open source so if you have fix it, you can make a pull request.
